<<<<<<< HEAD
# Generated by Django 4.1.3 on 2022-12-22 12:51
=======
# Generated by Django 4.1.3 on 2022-12-22 10:19
>>>>>>> f081807df9177816599ff996a33c18d24a9e0364

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_table_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
